### ISSUE TITLE
[Suggestion] Dedicated GitHub Actions for Improved Maintainability of Data Update Workflow

### ISSUE THREAD

**Issue by kevinmatthes** [sdruskat/cfftracker#5]
I would like to suggest you the following GitHub Actions because I think that they would enhance both the readability and the maintainability of the GitHub Action workflow for the daily data update.

- `py-actions/py-dependency-install@v4.0.0`:  install all Python software requirements listed in the `requirements.txt` located in the repository root; updates `pip`, `wheel`, and `setuptools` automatically, by default
- `fregante/setup-git-user@v1.1.0`:  setup up the GitHub Actions bot as authoring instance

Example:

```yaml
# Line 34:
      - name: Install Python requirements
        if: steps.cache.outputs.cache-hit != 'true'
        uses: py-actions/py-dependency-install@v4.0.0

# Line 48:
      - name: Configure GitHub Actions bot
        uses: fregante/setup-git-user@v1.1.0

      - name: Commit updated files
        run: git add -A && git commit -m 'Update data'
```

If you are interested, I can submit a Pull Request with the respective changes.
